services:
  # NORDVPN
  vpn:
    image: ghcr.io/bubuntux/nordvpn # this image is based on alpine and has nordvpn cli installed
    container_name: nordvpn
    cap_add: [NET_ADMIN, NET_RAW] # required for nordvpn to work
    devices:
      - /dev/net/tun
    environment:
      - TOKEN=${NORDVPN_TOKEN}
      - CONNECT=Peru
      - TECHNOLOGY=NordLynx
      # Allows communication between containers in the same network
      # 172.0.0.0/8 is the default subnet for docker networks, and
      # 192.168.0.0/16 is a common private IP range used in home networks
      - NETWORK=172.0.0.0/8,192.168.0.0/16, 172.19.0.0/16
    ports:
      # seace-runner ports 
      - "3000:3000"
    networks:
      - internal
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-fs", "https://nordvpn.com"]
      interval: 60s
      timeout: 10s
      start_period: 30s
      retries: 3
  
  seace-runner:
    build:
      context: ./seace-runner
    container_name: seace-runner
    # shares the network of the vpn container, so all traffic goes through the vpn (Peru)
    network_mode: "service:vpn"
    env_file:
      - .env
    volumes:
      - ./seace-runner/debug:/app/debug
      - ./seace_downloads:/app/downloads
    depends_on:
      - vpn
    environment:
      - AUTH_TOKEN=${SEACE_AUTH_TOKEN}
    restart: unless-stopped
  
  # PDF EXTRACTOR
  pdf-extractor:
    build:
      context: ./pdf-extractor
    container_name: pdf-extractor
    ports:
      - "8000:8000"
    volumes:
      - ./seace_downloads:/app/downloads
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    networks:
      - internal
    restart: unless-stopped

networks:
  internal:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.mtu: "1420" # MTU is set to 1420 to avoid fragmentation issues with the VPN connection